USE [master]
GO

/****** Object:  Database [Sklep Internetowy]    Script Date: 28.01.2024 08:33:51 ******/
CREATE DATABASE [Sklep Internetowy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sklep Internetowy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sklep Internetowy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Sklep Internetowy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Sklep Internetowy_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sklep Internetowy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sklep Internetowy] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sklep Internetowy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sklep Internetowy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sklep Internetowy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sklep Internetowy] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sklep Internetowy] SET  MULTI_USER 
GO

ALTER DATABASE [Sklep Internetowy] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sklep Internetowy] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sklep Internetowy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sklep Internetowy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Sklep Internetowy] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sklep Internetowy] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Sklep Internetowy] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sklep Internetowy] SET  READ_WRITE 
GO

